import time
y = time.gmtime()
readf = open('users.txt', 'r')
writef = open('users.txt', 'w')
print(y)
filelines = readf.read()
f = filelines.replace("//scratch.mit.edu/users/", "")
f = f.replace("https:", "")
f = f.replace("http:", "")
f = f.replace("/", "")
print(f)
# writef.write(f)
writef.close()
readf.close()
print(time.gmtime())
